//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {

        }

        public Comment(Comment comment)
        {
            CommentId = comment.CommentId;
            CommentNumber = comment.CommentNumber;
            CommentParentNumber = comment.CommentParentNumber;
            UserId = comment.UserId;
            ImageId = comment.ImageId;
            CommentText = comment.CommentText;
            CommentDate = comment.CommentDate;
        }

        public int CommentId { get; set; }
        public int CommentNumber { get; set; }
        public int CommentParentNumber { get; set; }
        public int UserId { get; set; }
        public int ImageId { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual User User { get; set; }
    }
}
