//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Comment = new HashSet<Comment>();
            this.Tag = new HashSet<Tag>();
        }

        public Image(Image image)
        {
            ImageId = image.ImageId;
            UserId = image.UserId;
            ImagePicture = image.ImagePicture;
            this.Comment = new HashSet<Comment>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int ImageId { get; set; }
        public int UserId { get; set; }
        public byte[] ImagePicture { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
