//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Image = new HashSet<Image>();
        }

        public Tag(Tag tag)
        {
            TagId = tag.TagId;
            TagName = tag.TagName;
            this.Image = new HashSet<Image>();
        }

        public int TagId { get; set; }
        public string TagName { get; set; }
    
        public virtual ICollection<Image> Image { get; set; }
    }
}
